PRAGMA ENCODING     = "UTF-8";
PRAGMA FOREIGN_KEYS = ON;

/* Статусы документов */
CREATE TABLE IF NOT EXISTS STATUSES (
    StatusID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    StatusName TEXT    NOT NULL
);
INSERT OR IGNORE INTO  STATUSES (StatusID, StatusName) VALUES (0, '<не указан>');
INSERT OR IGNORE INTO  STATUSES (StatusID, StatusName) VALUES (1, 'действует');

/* Типы документов */
CREATE TABLE IF NOT EXISTS TYPES (
    TypeID   INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    TypeName TEXT    NOT NULL
);
INSERT OR IGNORE INTO  TYPES (TypeID, TypeName) VALUES (0, '<не указан>');
INSERT OR IGNORE INTO  TYPES (TypeID, TypeName) VALUES (1, 'ГОСТ');
INSERT OR IGNORE INTO  TYPES (TypeID, TypeName) VALUES (2, 'ГОСТ Р');
INSERT OR IGNORE INTO  TYPES (TypeID, TypeName) VALUES (3, 'ГОСТ IEC');
INSERT OR IGNORE INTO  TYPES (TypeID, TypeName) VALUES (4, 'ГОСТ Р ИСО');

/* Список документов */
CREATE TABLE IF NOT EXISTS DOCUMENTS (
    DocID       INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    StatusID    INTEGER  NOT NULL DEFAULT 0,
    TypeID      INTEGER  NOT NULL DEFAULT 0,
    DocNum      TEXT     NOT NULL,
    DocYear     TEXT     NOT NULL,
    DocName     TEXT     NOT NULL,
    DocDate     DATETIME NOT NULL,
    Note        TEXT    ,
    ControlDate DATETIME NOT NULL,
    CONSTRAINT FK_DOCUMENTS_STATUSID FOREIGN KEY (StatusID) REFERENCES STATUSES(StatusID) ON UPDATE CASCADE ON DELETE SET DEFAULT,
    CONSTRAINT FK_DOCUMENTS_TYPEID   FOREIGN KEY (TypeID)   REFERENCES TYPES(TypeID)      ON UPDATE CASCADE ON DELETE SET DEFAULT
);

/* Поправки и изменения */
CREATE TABLE IF NOT EXISTS ADDONS (
    AddonID   INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
    AddonDate DATETIME NOT NULL,
    AddonName TEXT     NOT NULL,
    AddonNum  TEXT    ,
    AddonNote TEXT    ,
    DocID     INTEGER  NOT NULL,
    CONSTRAINT FK_ADDONS_DOCID FOREIGN KEY (DocID) REFERENCES DOCUMENTS(DocID) ON UPDATE CASCADE ON DELETE CASCADE
);
